micronaut:
  application:
    name: cs50FitnessFrenzy
  server:
    cors:
      enabled: true
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/cs50`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:root}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true